// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PrescriptionListController from "./prescription_list_controller"
application.register("prescription-list", PrescriptionListController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import ShowQrModalController from "./show_qr_modal_controller"
application.register("show-qr-modal", ShowQrModalController)

import StopPropagationController from "./stop_propagation_controller"
application.register("stop-propagation", StopPropagationController)
