meta_name: "Prescriptool"
meta_title: "Web app that generates unique prescriptions"
meta_description: "With Prescriptool, you can access all your prescriptions and search for a particular one."
meta_image: "ogimage.png"
